Advanced OOP
empa-scientific-it/python-tutorial pull request #156
Opened 2023-11-15 13:58 UTC by despadam

2023-12-10 18:16 UTC, edoardob90 requested changes
Thanks, @despadam 👏🏻  Thorough and the exercises are very much in line with the topics you covered.

I left you a few comments on how to improve the tests.

2023-12-10 18:16 UTC, edoardob90 commented on object_oriented_programming_advanced.ipynb
I made changes to the notebook (mostly rewordings) in a separate commit. Changes were simple enough that was much quicker.

2023-12-11 09:05 UTC, despadam commented on object_oriented_programming_advanced.ipynb
Looks good, thanks a lot!

2023-12-11 13:23 UTC, despadam commented
Thanks @edoardob90 for your comments! They have all been addressed. Could you please do a last check that everything works properly?

2023-12-11 13:33 UTC, edoardob90 approved these changes
Great! 💯

2023-12-11 13:33 UTC, merged