New material/parallelism 1
empa-scientific-it/python-tutorial pull request #171
Opened 2023-12-11 15:06 UTC by baffelli

Closes #10

2023-12-11 19:37 UTC, despadam commented
@baffelli Please double-check that my commit updates the skeleton of exercise 1 correctly. I used the code from the latest version of [the old branch](https://github.com/empa-scientific-it/python-tutorial/blob/new-material/parallelism/threads.ipynb). Without these changes, the notebook could not run.

2023-12-12 01:09 UTC, despadam requested changes
Thank you @baffelli for the great work! Most of the following are fixes for typos. However, as mentioned in my comments, I faced issues while running a couple of examples. I was also not able to pass the tests for the exercises. Would be great if you could double-check them, and then also show me what it is that perhaps I'm missing.

2023-12-12 07:02 UTC, baffelli commented on threads.ipynb
> +    "\n",
Done in c1bbcca

2023-12-12 07:04 UTC, baffelli commented on threads.ipynb
> +    "### Quiz: parallel or not\n",
Done in 577747e

2023-12-12 07:32 UTC, baffelli commented on threads.ipynb
> +    "In most cases, processes are managed by the operating system, which takes care of scheduling what process should currently run and takes care that no process can run forever and regularly yields
Changed in 148be2a

2023-12-12 07:32 UTC, baffelli commented on threads.ipynb
> +    "Because of shared memory, a thread is usually lighter in its resource usage than a process, moreover the shared memory means that multiple threads can communicate using shared variables, althoug
Changed in 148be2a

2023-12-12 07:50 UTC, baffelli commented on threads.ipynb
> +   "cell_type": "code",
I don't get this problem. This is strange.

2023-12-12 07:50 UTC, baffelli commented on threads.ipynb
> +   "cell_type": "code",
Same as above

2023-12-12 08:16 UTC, baffelli commented on threads.ipynb
> +   "cell_type": "code",
It worked for me.

2023-12-12 08:17 UTC, baffelli commented on threads.ipynb
> +   "cell_type": "code",
I got the output myself. It is strange

2023-12-12 09:04 UTC, yakutovicha commented
I set the PR "ready for review" since in fact it has been reviewed.

2023-12-12 09:05 UTC, baffelli commented
> I set the PR "ready for review" since in fact it has been reviewed.

Wait, there are a couple of things that should be fixed still. Some of the problems with running the code that @despadam had should be investigated.

2023-12-12 09:10 UTC, yakutovicha commented
> Wait, there are a couple of things that should be fixed still. Some of the problems with running the code that @despadam had should be investigated.

But "Ready for review" means only that it is ready for review, nothing more than that. We merge things only when they are approved.

2023-12-12 09:15 UTC, despadam commented
Yes, just reviewing for now. Not merging yet, but it shouldn't be a draft anymore.

2023-12-12 14:37 UTC, despadam requested changes
Just a small typo in the Quiz

2023-12-12 14:37 UTC, despadam commented on tutorial/threads.py
> +                "Parallel:": "What if the cashier is slow?",
```suggestion
                "Parallel": "What if the cashier is slow?",
```

2023-12-12 14:38 UTC, baffelli commented on tutorial/tests/test_threads.py
> +    rng = 30
I changed this to 50

2023-12-12 14:39 UTC, despadam commented
For me the examples in the section **High-level interface: Process pools** cannot run. I get the following error in the console:

`
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "C:\Users\adde\AppData\Local\miniconda3\envs\python-tutorial\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\adde\AppData\Local\miniconda3\envs\python-tutorial\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\adde\AppData\Local\miniconda3\envs\python-tutorial\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\adde\AppData\Local\miniconda3\envs\python-tutorial\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'task' on <module '__main__' (built-in)>
Process SpawnPoolWorker-3:
Traceback (most recent call last):
  File "C:\Users\adde\AppData\Local\miniconda3\envs\python-tutorial\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\adde\AppData\Local\miniconda3\envs\python-tutorial\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\adde\AppData\Local\miniconda3\envs\python-tutorial\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\adde\AppData\Local\miniconda3\envs\python-tutorial\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'task' on <module '__main__' (built-in)>
`

2023-12-12 14:50 UTC, despadam submitted a review, later dismissed

2023-12-12 14:52 UTC, despadam commented
As agreed with @baffelli, it is best to merge and see if the examples and exercises will work on Binder, as this is the most pressing matter. It appears that the errors as OS dependent, so let's make sure that it will work online and then we can discourage the participants from running the tutorial locally, for this section at least.

2023-12-12 14:55 UTC, baffelli commented
Let's try it [here](https://mybinder.org/v2/gh/empa-scientific-it/python-tutorial/new-material/parallelism-1)

2023-12-12 21:13 UTC, edoardob90 commented
Binder is unfortunately down now, and the error @despadam mentioned happens on my two machines as well. Not sure what we can do.

2023-12-12 21:20 UTC, edoardob90 commented on threads.ipynb
> +   "cell_type": "code",
Doesn't work for me either. Hangs indefinitely and cannot find the name `task`

2023-12-12 21:27 UTC, yakutovicha commented on threads.ipynb
> +   "cell_type": "code",
Doesn't work :(

2023-12-12 21:34 UTC, baffelli commented
> Binder is unfortunately down now, and the error @despadam mentioned happens on my two machines as well. Not sure what we can do.

That's really unfortunate. It seems to be highly OS dependent or maybe it's just a special case that runs on VSCode with the Jupiter extension. It might be that they implement a different Ipython kernel. I hope it works on Binder tomorrow, if not I'll try to walk people through examples in order to fill at least 1.5 hours

2023-12-12 21:59 UTC, edoardob90 commented on threads.ipynb
> +    "  alt=\"The beautiful MDN logo.\">\n",
```suggestion
    "  alt=\"A schema of parallelism and concurrency\">\n",
```

2023-12-12 21:59 UTC, edoardob90 commented on threads.ipynb
> +    "  <figcaption>A simple time diagram illustrating the difference between parallelism and concurrency (source: https://openclassrooms.com/en/courses/5684021-scale-up-your-code-with-java-concurrenc
```suggestion
    "  <figcaption>A simple time diagram illustrating the difference between parallelism and concurrency (<a href=\"https://openclassrooms.com/en/courses/5684021-scale-up-your-code-with-java-concurrency/5684028-identify-the-advantages-of-concurrency-and-parallelism\">Source</a>)</figcaption>\n",
```

2023-12-12 21:59 UTC, edoardob90 commented on threads.ipynb
> +    "    If this fails, you could try just-in-time compilers like numba, which only require you to add a decorator to existing functions. Only if all these steps yield no improvement should you attem
```suggestion
    "    <h4><b>Warning</b></h4> Multiprocessing/parallelism should be the last resort to improve the performance of your Python code. \n",
    "    You first should try improving your code by using the appropriate algorithms or by adopting numerical libraries like NumPy that offers vectorized operations. \n",
    "    If this fails, you could try just-in-time compilers like <a href=\"https://numba.pydata.org\">Numba</a>, which only requires you to decorate existing functions. Only if all these steps yield no improvement, should you attempt to use multiprocessing explicitly. \n",
```

2023-12-12 22:00 UTC, edoardob90 commented
Minor changes to the text. Still, I **cannot** make the notebook work with any Python version I tested. I'm sure I'm missing something in the setup, but for me the entire notebook is in a "broken" state.

2023-12-13 07:53 UTC, despadam approved these changes
Fingers crossed

2023-12-13 07:54 UTC, merged