Functions: test keyword parameter
empa-scientific-it/python-tutorial pull request #222
Opened 2024-04-18 15:27 UTC by despadam

2024-04-19 13:01 UTC, baffelli requested changes
We should consider how to deal with multiple asserts. 
Only the first assertion to fail is shown in the results. This is a design limitation of pytest

2024-04-22 09:32 UTC, baffelli submitted a review, later dismissed
The representation of the error is not ideal, but I suspect there's no better easy way to solve this.

2024-04-25 09:14 UTC, despadam commented on tutorial/tests/test_functions.py
> +    assert not errors
The latest commit prints the errors in this way:
![Capture](https://github.com/empa-scientific-it/python-tutorial/assets/16343312/635f6446-b021-4580-81ec-40b8400068dc)

2024-04-25 09:23 UTC, baffelli commented on tutorial/tests/test_functions.py
> +    assert not errors
I like this a lot!
Can you add a bullet list and a title?
Thank you again!

2024-04-26 09:11 UTC, despadam commented on tutorial/tests/test_functions.py
> +    assert not errors
![image](https://github.com/empa-scientific-it/python-tutorial/assets/16343312/fa06eae8-84ed-4d8d-9a9f-effec5def080)

2024-04-26 09:42 UTC, baffelli reviewed
Perfect. Only suggestion would be to avoid displaying the assertion below the list, but I'm not sure whether this is possible.

2024-04-26 11:08 UTC, despadam commented
> Perfect. Only suggestion would be to avoid displaying the assertion below the list, but I'm not sure whether this is possible.

To do that, we would have to change how the test output is displayed in general, but I do not want to touch that now. I think in general testsuite needs some fixes (there are probably some related issues already) but I would prefer to address that in a separate PR after the tutorial, to be safe.

So for now, if you approve, I would merge this PR as is.

2024-05-03 09:17 UTC, merged