Integrate of AI in testsuite
empa-scientific-it/python-tutorial pull request #248
Opened 2024-10-17 15:20 UTC by edoardob90

Main goal is to improve the feedback given when a test fails. This PR will supersede #68, integrating Copilot-level explanations of any error traceback obtained when running the tests.

Here's an example of the preliminary results on some examples in the `intro.ipynb` notebook:

<img width="1101" alt="image" src="https://github.com/user-attachments/assets/384df06b-110d-4a19-800b-82814a627f09">

### Notes

- **Minimum requirement** is a valid API key from OpenAI. It should be "loaded" with the utility function `set_key()` inside the module `tutorial.enable_ai`
- The initial prompt collates the function's code (anything that belongs to a `solution_*` function) and the traceback returned by `pytest`. Given this context, the model sometimes provides a step-by-step solution (if the task is easy)
- Asking for an explanation triggers the API, hence the function call is cached if the query is the same (function's code + traceback). There's no way to call the API again without changing the solution code.

### TODO

- [ ] Improve the prompt, making it less prone to provide a super-detailed solution
- [ ] Better way of handling the API key secret
- [ ] ...

2024-10-18 06:56 UTC, edoardob90 commented
Right now, to set the API key one must do:

```python
from tutorial.ai import config
API_KEY = "sk-*******" # your key
config(API_KEY)
```

Two more options, maybe useful for testing:
- `model`: change default model (default: `gpt-4o-mini`)
- `language`: the default language the model will use (default: English)

2024-10-23 17:36 UTC, edoardob90 commented
### TODO

- [ ] Add relevant `AIExplanation` objects when other errors occur (like `TEST_ERROR` as discussed in #253)
- [ ] Add a customizable config from a file saved on disk (to avoid manual setting in every notebook)
- [ ] Enable a custom query (the main logic is already there)

2024-10-30 18:50 UTC, edoardob90 commented
Check out #257 to an alternative (better?) to the caching mechanism.

2024-11-15 21:14 UTC, edoardob90 commented
WIP to merge #260 first before double-checking that everything works as expected

2024-11-20 08:59 UTC, edoardob90 commented
PR #260 changed substantially the UI of the tests (including more pytest output added to the test result output) and the AI widgets. Please, give your feedback on whether there's some "mismatch" in the UI.

A couple of things I'm still considering to review:
- The "Reveal solution" box: it doesn't use a dropdown anymore. Maybe it was better before?
- The AI explanation steps: they still use `ipywidgets.Accordion`. Maybe a tab-view is better since it's more compact but organized?

2024-11-22 08:37 UTC, Snowwpanda commented
Missing depencencies: python-dotenv, markdown2, openai, tenacity should be added to the environment list.

2024-11-22 10:24 UTC, edoardob90 commented
> Missing depencencies: python-dotenv, markdown2, openai, tenacity should be added to the environment list.

Done in 402cff0

2024-11-22 13:07 UTC, edoardob90 commented
> I am trying to test this with the `object-oriented` notebook. Here I provided a solution that is syntactically correct, but clearly wrong and I get no output at all:
> 
> ![image](https://private-user-images.githubusercontent.com/16343312/388932970-a9dd7a47-ad5c-4c05-bd47-85c10140cf78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyODA4NDUsIm5iZiI6MTczMjI4MDU0NSwicGF0aCI6Ii8xNjM0MzMxMi8zODg5MzI5NzAtYTlkZDdhNDctYWQ1Yy00YzA1LWJkNDctODVjMTAxNDBjZjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDEzMDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZjdmNzhiODU4ZGEyN2U5ZmUyYTQ3ZjdhMGQ5MDNkYTk1NmU5MjgxNDEwM2Y4NTk3NjQ0NWY2MDBiN2NhMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ntEKhEVm_abZRQdLDhBAqKezKlwOkfjn2nEvl0rb9kY)

Thanks, Despina, that was a very well-hidden bug.

In general, you can use `%%ipytest debug` and our cell magic will spit out any output from IPython, that we suppress by default.

2024-11-22 13:12 UTC, Snowwpanda requested changes
Nice work, some things i found i commented below, mainly missing packages. I may have a second look later.

2024-11-22 13:14 UTC, Snowwpanda commented on tutorial/tests/testsuite/helpers.py
> +                                this.style.display = 'none';
This may actually be more convoluted, i'm fine if we ignore the problem for now

2024-11-22 13:16 UTC, Snowwpanda approved these changes

2024-11-22 14:23 UTC, edoardob90 commented on tutorial/tests/testsuite/testsuite.py
> +        display(HTML(message))
Addressed with 0a60172

2024-11-22 14:29 UTC, edoardob90 commented on tutorial/tests/testsuite/testsuite.py
> +            "in the file <code>openai.env</code>. "
Done 1313e1e

2024-11-22 18:05 UTC, edoardob90 commented
@Snowwpanda @despadam If you could give a final check, then I guess we're good 🙏🏻

2024-11-24 11:29 UTC, despadam commented
> PR #260 changed substantially the UI of the tests (including more pytest output added to the test result output) and the AI widgets. Please, give your feedback on whether there's some "mismatch" in the UI.
> 
> A couple of things I'm still considering to review:
> 
> * The "Reveal solution" box: it doesn't use a dropdown anymore. Maybe it was better before?
> * The AI explanation steps: they still use `ipywidgets.Accordion`. Maybe a tab-view is better since it's more compact but organized?

Also, I agree with both suggestions here:
1. Being able to reveal/hide the solution
2. Tabs instead of accordion for the AI explanation

However, none of these is a priority, so I am happy if we merge it as it is and update these at a later point.

2024-11-25 09:16 UTC, edoardob90 commented
> Thanks for the great work, @edoardob90 ! My only comment is that (with AI or without) if I press `reveal solution` once in any exercise, then when I try to do it again in another exercise, it will not be revealed. Is there maybe an internal counter or flag somewhere that handles this? Perhaps this issue is also related to @Snowwpanda 's comment above.

This is clearly a bug then, I need to check it carefully. I bet it's some JS or CSS. I'll do it after finishing some materials update otherwise we're going to be too late with that.

2024-11-25 10:13 UTC, edoardob90 commented
The issue was with the new styling of the "Reveal" action. I fixed it, but I think it's better to restore the old collapsible layout. I left the new styling as a reference for now. We might want to remove it if it's unnecessary.

2024-11-25 10:15 UTC, edoardob90 commented on tutorial/tests/testsuite/helpers.py
> +                                this.style.display = 'none';
See [comment](https://github.com/empa-scientific-it/python-tutorial/pull/248#issuecomment-2497525168).

2024-11-25 10:53 UTC, despadam approved these changes
Works perfectly fine for me now. I believe we can go ahead and merge 🚀

2024-11-25 11:20 UTC, edoardob90 commented
Great, let's go. If a last-minute bug comes up, we'll fix it.

2024-11-25 11:22 UTC, merged