Fix/55
empa-scientific-it/python-tutorial pull request #90
Opened 2023-04-24 11:33 UTC by baffelli

Fixes #55

2023-04-24 11:55 UTC, edoardob90 requested changes
Just adjust the TOC itself

2023-04-24 11:55 UTC, edoardob90 commented on control_flow.ipynb
> +    "  - [The `try-except` block](#The-try-except-block)\n",
```suggestion
    "- [References](#References)\n",
    "- [Conditionals](#Conditionals)\n",
    "- [The `while` loop](#The-while-loop)\n",
    "- [The `for` loop](#The-for-loop)\n",
    "    - [The `enumerate` built-in](#The-enumerate-built-in)\n",
    "    - [The `range` built-in](#The-range-built-in)\n",
    "- [Nested loops](#Nested-loops)\n",
    "- [Altering loops](#Altering-loops)\n",
    "    - [`if` statement inside `for`/`while`](#if-statement-inside-for/while)\n",
    "    - [The `break` keyword](#The-break-keyword)\n",
    "    - [The `continue` keyword](#The-continue-keyword)\n",
    "    - [`else` after a `for`/`while`](#else-after-a-for/while)\n",
    "- [Exceptions](#Exceptions)\n",
    "    - [The `try-except` block](#The-try-except-block)\n",
```

Adjust the TOC. No need to include a link to the TOC itself, I think. **Double-check** that it renders correctly.

2023-04-25 07:58 UTC, baffelli reviewed
The TOC fix worked.

2023-04-25 09:49 UTC, yakutovicha requested changes
A few very small changes, otherwise good to go 👍

2023-04-25 09:49 UTC, yakutovicha commented on control_flow.ipynb
> +    "Often,  you need to iterate through a collection, operate on the current value while keeping track of the *position* (index) of the loop.\n",
```suggestion
    "Often, you need to iterate through a collection and operate on each value while keeping track of the *position* (index) of the loop.\n",
```

2023-04-25 09:49 UTC, yakutovicha commented on control_flow.ipynb
> +    "In other languages, you would define an index variable and increment it at every loop. While this is possible in python as shown in the previous code snippet, we usually prefer to use the built-
```suggestion
    "In other languages, you would define an index variable and increment it at every loop. While this is possible in Python, as shown in the previous code snippet, we usually prefer to use the built-in `enumerate` function, documented [here](https://docs.python.org/3/library/functions.html#enumerate).\n",
```

2023-04-25 10:06 UTC, edoardob90 approved these changes

2023-04-25 11:20 UTC, yakutovicha approved these changes

2023-04-25 11:22 UTC, merged