Fix/64
empa-scientific-it/python-tutorial pull request #92
Opened 2023-04-24 11:37 UTC by baffelli

Fixes #64

2023-04-24 11:59 UTC, edoardob90 requested changes
Just a minor change, for readability

2023-04-24 11:59 UTC, edoardob90 commented on functional_programming.ipynb
> +    "            The operator <code>%</code> (modulo) gives the remainder of division. <code>a % k</code> is 0 when a is a multiple of <code>k</code>. \n",
```suggestion
    "            The operator <code>%</code> (modulo) gives the remainder of division. <code>a % k</code> is 0 when <code>a</code> is a multiple of <code>k</code>. \n",
```

2023-04-25 08:00 UTC, baffelli commented on functional_programming.ipynb
> +    "            The operator <code>%</code> (modulo) gives the remainder of division. <code>a % k</code> is 0 when a is a multiple of <code>k</code>. \n",
Thanks, looks good

2023-04-25 10:02 UTC, yakutovicha requested changes
Two minor requests.

2023-04-26 14:51 UTC, baffelli commented on functional_programming.ipynb
> +    "            The operator <code>%</code> (modulo) gives the remainder of division. <code>a % k</code> is 0 when <code>a</code> is a multiple of <code>k</code>. \n",
Fixed with a comment in 12604ab. Unfortunately I cannot add internal link using markdown here, I tried with HTML links but it did not work.

2023-04-26 18:28 UTC, yakutovicha approved these changes
LGTM!

2023-04-26 19:36 UTC, edoardob90 approved these changes

2023-04-26 19:38 UTC, merged