Explain input args to solution functions
empa-scientific-it/python-tutorial pull request #93
Opened 2023-04-24 12:29 UTC by edoardob90

Fixes #46

2023-04-25 14:47 UTC, yakutovicha requested changes
Thanks, @edoardob90. I added below a few comments.

Also, shouldn't we remove the Quarto slides annotations from this notebook too?

2023-04-25 14:47 UTC, yakutovicha commented on intro.ipynb
> +    "- Reply **in a thread** if you want to add a comment to another question\n",
```suggestion
    "- Reply **in a thread** if you want to add a comment to a question\n",
```
It doesn't matter which question, I believe.

2023-04-25 14:47 UTC, yakutovicha commented on intro.ipynb
> +    "Let's look at one important detail about exercises: the variables you are expected to work with in **your solution**.\n",
```suggestion
    "Let's look at one important detail about exercises: the variables in **your solution** you are expected to work with.\n",
```

2023-04-25 15:20 UTC, edoardob90 commented
> Thanks, @edoardob90. I added below a few comments.
> 
> Also, shouldn't we remove the Quarto slides annotations from this notebook too?

Well, I do want to have slides for the intro, not just a notebook: there's no Python code to evaluate. If you want a notebook, than I'll move the slides stuff under `slides/` and leave the notebook without any annotation.

2023-04-25 16:06 UTC, edoardob90 commented
Done! ✅

2023-04-26 12:53 UTC, baffelli reviewed
Suggested a small change on how to run the cell.

2023-04-26 17:16 UTC, edoardob90 commented on slides/intro_slides.ipynb
> +    "\n",
👍🏻 I think we will see that in detail after the intro, since we're doing a "warm up" session on Jupyter only

2023-04-26 17:17 UTC, merged